//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class GlobalConfigMgrWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(GlobalConfigMgr), typeof(MonoSingleton<GlobalConfigMgr>));
		L.RegFunction("RegisterAnimationState", RegisterAnimationState);
		L.RegFunction("GetLuaCnsCfg", GetLuaCnsCfg);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RegisterAnimationState(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			GlobalConfigMgr obj = (GlobalConfigMgr)ToLua.CheckObject<GlobalConfigMgr>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.RegisterAnimationState(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetLuaCnsCfg(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			GlobalConfigMgr obj = (GlobalConfigMgr)ToLua.CheckObject<GlobalConfigMgr>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			LuaCnsConfig o = obj.GetLuaCnsCfg(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

