//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class LuaCnsConfigWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(LuaCnsConfig), typeof(System.Object));
		L.RegFunction("CreateStateDef", CreateStateDef);
		L.RegFunction("CreateCmd", CreateCmd);
		L.RegFunction("CreateAICmd", CreateAICmd);
		L.RegFunction("GetAICommand", GetAICommand);
		L.RegFunction("GetStateDef", GetStateDef);
		L.RegFunction("New", _CreateLuaCnsConfig);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("HasStateDef", get_HasStateDef, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateLuaCnsConfig(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				LuaCnsConfig obj = new LuaCnsConfig();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: LuaCnsConfig.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CreateStateDef(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaCnsConfig obj = (LuaCnsConfig)ToLua.CheckObject<LuaCnsConfig>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			int o = obj.CreateStateDef(arg0);
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CreateCmd(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2)
			{
				LuaCnsConfig obj = (LuaCnsConfig)ToLua.CheckObject<LuaCnsConfig>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				Mugen.Cmd_Command o = obj.CreateCmd(arg0);
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 3)
			{
				LuaCnsConfig obj = (LuaCnsConfig)ToLua.CheckObject<LuaCnsConfig>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				string arg1 = ToLua.CheckString(L, 3);
				Mugen.Cmd_Command o = obj.CreateCmd(arg0, arg1);
				ToLua.PushObject(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: LuaCnsConfig.CreateCmd");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CreateAICmd(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2)
			{
				LuaCnsConfig obj = (LuaCnsConfig)ToLua.CheckObject<LuaCnsConfig>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				Mugen.AI_Command o = obj.CreateAICmd(arg0);
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 3)
			{
				LuaCnsConfig obj = (LuaCnsConfig)ToLua.CheckObject<LuaCnsConfig>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				string arg1 = ToLua.CheckString(L, 3);
				Mugen.AI_Command o = obj.CreateAICmd(arg0, arg1);
				ToLua.PushObject(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: LuaCnsConfig.CreateAICmd");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetAICommand(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaCnsConfig obj = (LuaCnsConfig)ToLua.CheckObject<LuaCnsConfig>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			Mugen.AI_Command o = obj.GetAICommand(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetStateDef(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaCnsConfig obj = (LuaCnsConfig)ToLua.CheckObject<LuaCnsConfig>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Mugen.CNSStateDef o = obj.GetStateDef(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_HasStateDef(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			LuaCnsConfig obj = (LuaCnsConfig)o;
			bool ret = obj.HasStateDef;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index HasStateDef on a nil value");
		}
	}
}

