//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Mugen_Cns_PhysicsTypeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(Mugen.Cns_PhysicsType));
		L.RegVar("none", get_none, null);
		L.RegVar("S", get_S, null);
		L.RegVar("C", get_C, null);
		L.RegVar("A", get_A, null);
		L.RegVar("N", get_N, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<Mugen.Cns_PhysicsType>.Check = CheckType;
		StackTraits<Mugen.Cns_PhysicsType>.Push = Push;
	}

	static void Push(IntPtr L, Mugen.Cns_PhysicsType arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(Mugen.Cns_PhysicsType), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_none(IntPtr L)
	{
		ToLua.Push(L, Mugen.Cns_PhysicsType.none);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_S(IntPtr L)
	{
		ToLua.Push(L, Mugen.Cns_PhysicsType.S);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_C(IntPtr L)
	{
		ToLua.Push(L, Mugen.Cns_PhysicsType.C);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_A(IntPtr L)
	{
		ToLua.Push(L, Mugen.Cns_PhysicsType.A);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_N(IntPtr L)
	{
		ToLua.Push(L, Mugen.Cns_PhysicsType.N);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		Mugen.Cns_PhysicsType o = (Mugen.Cns_PhysicsType)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

