//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Mugen_Cns_TypeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(Mugen.Cns_Type));
		L.RegVar("none", get_none, null);
		L.RegVar("S", get_S, null);
		L.RegVar("C", get_C, null);
		L.RegVar("A", get_A, null);
		L.RegVar("L", get_L, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<Mugen.Cns_Type>.Check = CheckType;
		StackTraits<Mugen.Cns_Type>.Push = Push;
	}

	static void Push(IntPtr L, Mugen.Cns_Type arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(Mugen.Cns_Type), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_none(IntPtr L)
	{
		ToLua.Push(L, Mugen.Cns_Type.none);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_S(IntPtr L)
	{
		ToLua.Push(L, Mugen.Cns_Type.S);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_C(IntPtr L)
	{
		ToLua.Push(L, Mugen.Cns_Type.C);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_A(IntPtr L)
	{
		ToLua.Push(L, Mugen.Cns_Type.A);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_L(IntPtr L)
	{
		ToLua.Push(L, Mugen.Cns_Type.L);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		Mugen.Cns_Type o = (Mugen.Cns_Type)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

